services:
  pianinni:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pianinni
    restart: unless-stopped
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
